"""initial schema

Revision ID: 0001
Revises:
Original create date: 2026-09-21 21:26:21.816576+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_events",
        sa.Column("max_event_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "done",
                "failed",
                name="ck_inbound_events_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("max_event_id"),
    )
    op.create_table(
        "management_companies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("region_code", sa.String(), nullable=False),
        sa.Column("ads_phone", sa.String(), nullable=True),
        sa.Column("ads_hours", sa.String(), nullable=True),
        sa.Column("is_test_data", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbound_messages",
        sa.Column("max_chat_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "failed",
                name="ck_outbound_messages_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problem_types",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "default_responsibility_zone",
            sa.Enum(
                "uk",
                "rso",
                "owner",
                "municipality",
                "unknown",
                name="ck_problem_types_default_responsibility_zone",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resolution_hours", sa.Integer(), nullable=True),
        sa.Column("norm_reference", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "resource_organizations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("region_code", sa.String(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "cold_water",
                "hot_water",
                "heating",
                "sewage",
                "electricity",
                "gas",
                name="ck_resource_organizations_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("contact", sa.String(), nullable=True),
        sa.Column("is_test_data", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("max_user_id", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("max_user_id"),
    )
    op.create_table(
        "consents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("consent_version", sa.Integer(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "houses",
        sa.Column("address_raw", sa.String(), nullable=False),
        sa.Column("fias_id", sa.String(), nullable=True),
        sa.Column("region_code", sa.String(), nullable=False),
        sa.Column("management_company_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["management_company_id"],
            ["management_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("source_key", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("region_code", sa.String(), nullable=True),
        sa.Column("management_company_id", sa.Uuid(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["management_company_id"],
            ["management_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "house_links",
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "house_resource_orgs",
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "cold_water",
                "hot_water",
                "heating",
                "sewage",
                "electricity",
                "gas",
                name="ck_house_resource_orgs_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_organization_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_organization_id"],
            ["resource_organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_text", sa.String(), nullable=False),
        sa.Column("chunk_meta", sa.JSON(), nullable=True),
        sa.Column("qdrant_point_id", sa.Uuid(), nullable=True),
        sa.Column(
            "index_state",
            sa.Enum(
                "pending",
                "indexed",
                "failed",
                name="ck_knowledge_chunks_index_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "planned_outage",
                "emergency_outage",
                name="ck_notifications_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "resource_type",
            sa.Enum(
                "cold_water",
                "hot_water",
                "heating",
                "sewage",
                "electricity",
                "gas",
                name="ck_notifications_resource_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "test_data",
                "manual",
                name="ck_notifications_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tickets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("management_company_id", sa.Uuid(), nullable=True),
        sa.Column("raw_text", sa.String(), nullable=False),
        sa.Column("problem_type", sa.String(), nullable=False),
        sa.Column(
            "responsibility_zone",
            sa.Enum(
                "uk",
                "rso",
                "owner",
                "municipality",
                "unknown",
                name="ck_tickets_responsibility_zone",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "routed_to_org_type",
            sa.Enum(
                "uk",
                "rso",
                "owner",
                "municipality",
                "unknown",
                name="ck_tickets_routed_to_org_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("routed_to_org_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "accepted",
                "in_progress",
                "routed_to_contractor",
                "completed",
                "merged",
                "needs_dispatcher",
                name="ck_tickets_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("embedding_point_id", sa.Uuid(), nullable=True),
        sa.Column("source_event_id", sa.Uuid(), nullable=True),
        sa.Column("dedup_group_id", sa.Uuid(), nullable=True),
        sa.Column("duplicate_of_ticket_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_tickets_confidence_range"
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["management_company_id"],
            ["management_companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_type"],
            ["problem_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["inbound_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_houses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "house_id"),
    )
    op.create_index(
        "ix_user_houses_one_primary_per_user",
        "user_houses",
        ["user_id"],
        unique=True,
        postgresql_where="is_primary",
    )
    op.create_table(
        "classification_logs",
        sa.Column("inbound_event_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column("message_masked", sa.String(), nullable=False),
        sa.Column("problem_type", sa.String(), nullable=False),
        sa.Column(
            "responsibility_zone",
            sa.Enum(
                "uk",
                "rso",
                "owner",
                "municipality",
                "unknown",
                name="ck_classification_logs_responsibility_zone",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("used_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("kb_version", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inbound_event_id"],
            ["inbound_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_type"],
            ["problem_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "failed",
                name="ck_notification_deliveries_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_events",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "accepted",
                "in_progress",
                "routed_to_contractor",
                "completed",
                "merged",
                "needs_dispatcher",
                name="ck_ticket_events_from_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "accepted",
                "in_progress",
                "routed_to_contractor",
                "completed",
                "merged",
                "needs_dispatcher",
                name="ck_ticket_events_to_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_subscribers",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_author", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "join_reason",
            sa.Enum(
                "author",
                "dedup_auto",
                "manual",
                name="ck_ticket_subscribers_join_reason",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id", "user_id"),
    )
    # ### end Alembic commands ###

    # Append-only ticket_events (architecture.md §5.2, db-001.md — «История
    # заявки не переписывается»): гарантия на уровне БД, не только в коде
    # приложения, которое легко обойти прямым запросом.
    op.execute(
        """
        CREATE FUNCTION ticket_events_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'ticket_events is append-only: % not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER ticket_events_no_update
        BEFORE UPDATE ON ticket_events
        FOR EACH ROW EXECUTE FUNCTION ticket_events_forbid_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER ticket_events_no_delete
        BEFORE DELETE ON ticket_events
        FOR EACH ROW EXECUTE FUNCTION ticket_events_forbid_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ticket_events_no_delete ON ticket_events;")
    op.execute("DROP TRIGGER IF EXISTS ticket_events_no_update ON ticket_events;")
    op.execute("DROP FUNCTION IF EXISTS ticket_events_forbid_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_subscribers")
    op.drop_table("ticket_events")
    op.drop_table("notification_deliveries")
    op.drop_table("classification_logs")
    op.drop_index(
        "ix_user_houses_one_primary_per_user",
        table_name="user_houses",
        postgresql_where="is_primary",
    )
    op.drop_table("user_houses")
    op.drop_table("tickets")
    op.drop_table("notifications")
    op.drop_table("knowledge_chunks")
    op.drop_table("house_resource_orgs")
    op.drop_table("house_links")
    op.drop_table("knowledge_documents")
    op.drop_table("houses")
    op.drop_table("consents")
    op.drop_table("users")
    op.drop_table("resource_organizations")
    op.drop_table("problem_types")
    op.drop_table("outbound_messages")
    op.drop_table("management_companies")
    op.drop_table("inbound_events")
    # ### end Alembic commands ###
